version: '2.2'

services:
  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:8.0.0-SNAPSHOT"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    env_file: [".env"]
    environment:
      - "discovery.type=single-node"
      - "cluster.name=dev-docker-cluster"
      - "xpack.license.self_generated.type=trial"
      - "xpack.security.enabled=true"
      - "xpack.security.http.ssl.enabled=false"
      - "xpack.security.transport.ssl.enabled=false"
      - "xpack.security.transport.ssl.verification_mode=none"
      - "bootstrap.memory_lock=true"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - "./cert-bundle:$ES_CERTS_DIR"
      - "esdata-8.0:/usr/share/elasticsearch/data"
    networks: ["esnet"]

  elasticsearch-proxy:
    image: "nginx:latest"
    env_file: [".env"]
    volumes: ["./nginx/es.conf:/etc/nginx/conf.d/es.conf:ro"]
    networks: ["esnet"]
    ports: ["9200:9200"]

  metricbeat:
    image: "docker.elastic.co/beats/metricbeat:8.0.0-SNAPSHOT"
    user: "root"
    env_file: [".env"]
    environment:
      - "DOCKER_HOST=unix:///var/run/docker.sock"
      - "ELASTICSEARCH_URL=$ELASTICSEARCH_HOSTS"
      - "ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES=$METRICBEAT_CERTS_DIR/ca/$VIRTUAL_HOST-ca.crt"
      - "METRICBEAT_KBN_SETUP_USERNAME=$METRICBEAT_KBN_SETUP_USERNAME"
      - "METRICBEAT_KBN_SETUP_PASSWORD=$METRICBEAT_KBN_SETUP_PASSWORD"
    volumes:
      - "./cert-bundle:$METRICBEAT_CERTS_DIR"
      - "./metricbeat/config:/usr/share/metricbeat/config:ro"
      - "./metricbeat/metricbeat.yml:/usr/share/metricbeat/metricbeat.yml:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks: ["esnet"]

volumes:
  esdata-8.0:
    driver: "local"

networks:
  esnet:
