version: '3.2'

services:
  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:8.4.0-SNAPSHOT"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    env_file: [".env"]
    environment:
      - "network.host=elasticsearch"
      - "discovery.type=single-node"
      - "cluster.name=dev-docker-cluster"
      - "xpack.license.self_generated.type=trial"
      - "xpack.security.enabled=true"
      - "xpack.security.http.ssl.enabled=true"
      - "xpack.security.http.ssl.key=$ELASTICSEARCH_CERTS_DIR/$DEV_HOSTNAME/$DEV_HOSTNAME.key"
      - "xpack.security.http.ssl.certificate=$ELASTICSEARCH_CERTS_DIR/$DEV_HOSTNAME/$DEV_HOSTNAME.crt"
      - "xpack.security.http.ssl.certificate_authorities=$ELASTICSEARCH_CERTS_DIR/ca/ca.crt"
      - "xpack.security.authc.api_key.enabled=true"
      - "bootstrap.memory_lock=true"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - "./cert-bundle:$ELASTICSEARCH_CERTS_DIR"
      - "esdata-8.4:/usr/share/elasticsearch/data"
    networks: ["esnet"]

  es-proxy:
    image: "nginx:latest"
    env_file: [".env"]
    volumes:
      - "./cert-bundle:$NGINX_CERTS_DIR"
      - "./nginx/es.conf:/etc/nginx/conf.d/es.conf:ro"
    networks: ["esnet"]
    ports: ["9200:9200"]

volumes:
  esdata-8.4:
    driver: "local"

networks:
  esnet:
