version: '2.2'

services:
  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.0.0-SNAPSHOT"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    env_file: [".env"]
    environment:
      - "discovery.type=single-node"
      - "cluster.name=dev-docker-cluster"
      - "xpack.license.self_generated.type=trial"
      - "xpack.security.enabled=true"
      - "xpack.security.http.ssl.enabled=false"
      - "xpack.security.transport.ssl.enabled=false"
      - "xpack.security.transport.ssl.verification_mode=none"
      - "bootstrap.memory_lock=true"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - "./cert-bundle:$ES_CERTS_DIR"
      - "esdata-7.0:/usr/share/elasticsearch/data"
    networks: ["esnet"]

  elasticsearch-proxy:
    image: "nginx:latest"
    env_file: [".env"]
    volumes: ["./nginx/es.conf:/etc/nginx/conf.d/es.conf:ro"]
    networks: ["esnet"]
    ports: ["9200:9200"]

volumes:
  esdata-7.0:
    driver: "local"

networks:
  esnet:
