# Set user passwords:
# [root@06306b40d436 elasticsearch]# ./bin/elasticsearch-setup-passwords interactive \
# -u https://localhost:9200 \
# -Expack.security.http.ssl.certificate_authorities=$ES_CERTS_DIR/ca/ca.crt

version: '2.2'

services:
  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:6.8.13"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    env_file: [".env"]
    environment:
      - "discovery.type=single-node"
      - "cluster.name=dev-docker-cluster"
      - "xpack.license.self_generated.type=trial"
      - "xpack.security.enabled=true"
      - "xpack.security.http.ssl.enabled=true"
      - "xpack.security.http.ssl.key=$ES_CERTS_DIR/$DEV_HOSTNAME/$DEV_HOSTNAME.key"
      - "xpack.security.http.ssl.certificate=$ES_CERTS_DIR/$DEV_HOSTNAME/$DEV_HOSTNAME.crt"
      - "xpack.security.http.ssl.certificate_authorities=$ES_CERTS_DIR/ca/ca.crt"
      - "xpack.security.transport.ssl.enabled=false"
      - "xpack.security.transport.ssl.verification_mode=none"
      - "bootstrap.memory_lock=true"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - "./cert-bundle:$ES_CERTS_DIR"
      - "esdata-6.8:/usr/share/elasticsearch/data"
    networks: ["esnet"]

  elasticsearch-proxy:
    image: "nginx:latest"
    env_file: [".env"]
    volumes:
      - "./cert-bundle:$NGINX_CERTS_DIR"
      - "./nginx/es.conf:/etc/nginx/conf.d/es.conf:ro"
    networks: ["esnet"]
    ports: ["9200:9200"]

  web:
    image: "nginx:latest"
    env_file: [".env"]
    volumes:
      - "./cert-bundle:$NGINX_CERTS_DIR"
      - "./nginx/web.conf:/etc/nginx/conf.d/web.conf:ro"
      - "./nginx/html:/etc/nginx/html:ro"
    ports: ["443:8080"]

volumes:
  esdata-6.8:
    driver: "local"

networks:
  esnet:
