metricbeat.config.modules:
  path: "${path.config}/modules.d/*.yml"

metricbeat.modules:
- module: docker
  metricsets:
    - "container"
    - "cpu"
    - "diskio"
    - "event"
    - "healthcheck"
    - "info"
    #- "image"
    - "memory"
    - "network"
  hosts: ["unix:///var/run/docker.sock"]
  period: 10s
  enabled: true

- module: kibana
  metricsets: ["stats"]
  period: 10s
  hosts: ["https://paninix:443/dev"]
  username: "${METRICBEAT_KBN_SETUP_USERNAME}"
  password: "${METRICBEAT_KBN_SETUP_PASSWORD}"
  ssl.certificate_authorities: ["${METRICBEAT_CERTS_DIR}/ca/ca.crt"]
  enabled: true

- module: linux
  period: 10s
  metricsets:
    - "pageinfo"
    - "memory"
    # - ksm
    # - conntrack
    # - iostat
  hostfs: /hostfs
  enabled: true

- module: elasticsearch
  metricsets:
    - node
    - node_stats
    - index
    #- index_recovery
    - index_summary
    - shard
    #- ml_job
  period: 10s
  hosts: ["${ELASTICSEARCH_URL}"]
  username: "${BEATS_WRITER_ES_USERNAME}"
  password: "${BEATS_WRITER_ES_PASSWORD}"
  ssl.certificate_authorities: ["${METRICBEAT_CERTS_DIR}/ca/ca.crt"]

  #index_recovery.active_only: true
  xpack.enabled: true
  #scope: node
  enabled: true

setup.kibana:
  host: "https://paninix:443/dev"
  username: "${METRICBEAT_KBN_SETUP_USERNAME}"
  password: "${METRICBEAT_KBN_SETUP_PASSWORD}"
  ssl.certificate_authorities: ["${METRICBEAT_CERTS_DIR}/ca/ca.crt"]

output.elasticsearch:
  hosts: "${ELASTICSEARCH_URL}"
  username: "${BEATS_WRITER_ES_USERNAME}"
  password: "${BEATS_WRITER_ES_PASSWORD}"
  ssl.certificate_authorities: ["${METRICBEAT_CERTS_DIR}/ca/ca.crt"]

xpack.monitoring:
  enabled: false
  elasticsearch:
    username: "${BEATS_SYSTEM_ES_USERNAME}"
    password: "${BEATS_SYSTEM_ES_PASSWORD}"
    ssl.certificate_authorities: ["${METRICBEAT_CERTS_DIR}/ca/ca.crt"]

setup.template.fields: "config/fields.yml"
